services:

  test_db:
    image: postgres:15
    container_name: story_taller_db
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    networks:
      - apps_net

  app:
    container_name: story_taller
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.docker
    volumes:
      - ./src/:/src
    command: bash -c "alembic upgrade head && python main.py"
    ports:
      - "8000:8000"
    networks:
      - apps_net
    depends_on:
      - test_db

networks:
  apps_net:
