"""authorization_system_models

Revision ID: 1ea5043458a7
Revises: 6627ba6d37d3
Create Date: 2024-08-11 00:29:11.268847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea5043458a7'
down_revision: Union[str, None] = '6627ba6d37d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_to_group_association_table',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('permission_id', 'permission_group_id')
    )
    op.add_column('user', sa.Column('permissions_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'permission_group', ['permissions_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'permissions_group_id')
    op.drop_table('permission_to_group_association_table')
    op.drop_table('permission_group')
    op.drop_table('permission')
    # ### end Alembic commands ###
