"""story_status

Revision ID: 6627ba6d37d3
Revises: a4e97a63e7de
Create Date: 2024-08-09 03:44:24.261062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from infrastructure.services.sql_db.models.content.story import StoryDB
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
revision: str = '6627ba6d37d3'
down_revision: Union[str, None] = 'a4e97a63e7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    statuses = postgresql.ENUM('DRAFT', 'PUBLIC', 'PRIVATE', name='storystatus', create_type=True)
    statuses.create(op.get_bind())
    op.add_column('story', sa.Column('status', statuses, default='DRAFT', nullable=True))
    session = Session(bind=op.get_bind())
    stmt = sa.select(StoryDB)
    stories = session.execute(stmt).scalars()
    for story in stories:
        story.status = 'DRAFT'
    session.commit()
    op.alter_column('story', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'status')
    sa_enum = postgresql.ENUM(name='storystatus')
    sa_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
